[package]
name = "nll_rs"
version = "0.1.0"
authors = ["Brandon Blaylock <brandon@blaylock.dev>"]
edition = "2018"
license = "MPL-2.0"
description = "A collection of utilities"
homepage = "https://github.com/nullpub/nll_rs"
repository = "https://github.com/nullpub/nll_rs"

[dependencies]
